version: "3.7"
services:
  mongo_db:
    container_name: backend_db
    build: ./mongodb
    ports:
      - "27017:${DB_PORT}"
    networks:
      net-10.9.0.0:
        ipv4_address: ${DB_HOST}

  api:
    container_name: backend_api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3001:${PORT}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_ADMIN=${DB_ADMIN}
      - DB_ADMIN_PASS=${DB_ADMIN_PASS}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
      - ALGORITHM_1_IP=${ALGORITHM_1_IP}
      - ALGORITHM_1_PORT=${ALGORITHM_1_PORT}
      - ALGORITHM_2_IP=${ALGORITHM_2_IP}
      - ALGORITHM_2_PORT=${ALGORITHM_2_PORT}      
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.4

    volumes:
      - ./api/:/api/dev
      - /api/dev/node_modules/

networks:
  net-10.9.0.0:
    name: net-10.9.0.0
    ipam:
      config:
        - subnet: 10.9.0.0/24
