version: "3.7"
services:
  mongo_db:
    container_name: backend_db
    build: ./mongodb
    ports:
      - "27017:${MONGO_PORT}"
    networks:
      net-10.9.0.0:
        ipv4_address: ${MONGO_HOST}

  api:
    container_name: backend_api
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3001:${PORT}"
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.4

    volumes:
      - ./api/:/api/dev
      - /api/dev/node_modules/

  sonarqube:
    container_name: backend_sonarqube
    build: ./sonarqube
    ports:
      - "9000:${SONARQUBE_PORT}"
    environment:
      - SONAR_JDBC_USERNAME=${SONARQUBE_DB_USERNAME}
      - SONAR_JDBC_PASSWORD=${SONARQUBE_DB_PASSWORD}
      - SONAR_EMBEDDEDDATABASE_PORT=${SONAR_EMBEDDEDDATABASE_PORT}

    volumes:
      - /opt/sonarqube/data
      - /opt/sonarqube/logs
      - /opt/sonarqube/extensions
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.10

  # sonarqube_local:
  #   container_name: sonarqube_local
  #   image: sonarsource/sonar-scanner-cli
  #   environment:
  #     - SONAR_HOST_URL="http://127.0.0.1:9000"
  #     - SONAR_LOGIN="ed04f7272339f3c8771e40e55e2f1d682e96c2da"
  #   networks: 
  #     - sonar_net


networks:
  net-10.9.0.0:
    name: net-10.9.0.0
    ipam:
      config:
        - subnet: 10.9.0.0/24
  sonar_net:
    driver: bridge
