version: 2.1

orbs:
  codecov: codecov/codecov@3
jobs:
  build:
    docker: 
      - image: cimg/node:current
    steps:
      - checkout
      - run:
        name: Install packages
        command: npm install
      - run:
        name: Run tests
        command: npm --version #TODO replace with test script once added. Ex: npm test 
      - codecov/upload
workflow:
  version: 2.1
  build-test: 
    jobs:
      - build