/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Assignment {
  course: {
    coursename?: string;
    noScheduleOverlap?: string[];
    lecturesNumber?: number;
    labsNumber?: number;
    tutorialsNumber?: number;
    capacity?: number;
    [k: string]: unknown;
  };
  prof: {
    name?: string;
    courses?: string[];
    timePreferences?: string[];
    coursePreferences?: number[];
    dayPreferences?: string[];
    equipmentPreferences?: string[];
    load?: number;
    [k: string]: unknown;
  };
  timeslot: {
    day?: string[];
    length?: number;
    startTime?: number;
    [k: string]: unknown;
  };
  room: {
    location?: string;
    capacity?: number;
    equipment?: string[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
