/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Coursesection {
  courseid: {
    /**
     * Course subject, e.g. SENG, CSC
     */
    subject: string;
    /**
     * Course code, e.g. 499,310
     */
    code: string;
    /**
     * Term course is offered in
     */
    term: 'FALL' | 'SPRING' | 'SUMMER';
    [k: string]: unknown;
  };
  /**
   * Hours per week course is offered
   */
  hoursPerWeek?: number;
  /**
   * Capacity of course
   */
  capacity: number;
  /**
   * Professor teaching course
   */
  professors: ({
    email: string;
    /**
     * password hashed in db
     */
    password: string;
    [k: string]: unknown;
  } & {
    name: string;
    /**
     * User roles
     */
    userrole: 'ADMIN' | 'TEACHER';
    [k: string]: unknown;
  })[];
  /**
   * Start date of course
   */
  startDate?: string;
  /**
   * End date of course
   */
  endDate?: string;
  meetingtimes: {
    days: ('MONDAY' | 'TUESDAY' | 'WEDNESDAY' | 'THURSDAY' | 'FRIDAY')[];
    startTime: string;
    endTime: string;
    [k: string]: unknown;
  };
  [k: string]: unknown;
}
