/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InputdataProfessors {
  name?: string;
  courses?: string[];
  timePreferences?: string[];
  coursePreferences?: number[];
  dayPreferences?: string[];
  equipmentPreferences?: string[];
  load?: number;
  index?: number;
  [k: string]: unknown;
}
