/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface InputdataCourses {
  coursename?: string;
  noScheduleOverlap?: string[];
  lecturesNumber?: number;
  labsNumber?: number;
  tutorialsNumber?: number;
  capacity?: number;
  [k: string]: unknown;
}
