/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface Success {
  /**
   * Success
   */
  success: boolean;
  /**
   * Success message
   */
  message: string;
  [k: string]: unknown;
}
