FROM node:lts

WORKDIR /api/dev

# A wildcard is used to ensure copying both package.json AND package-lock.json (when available).
# Copying this first prevents re-running npm install on every code change.
COPY package*.json ./

RUN npm install && npm cache clean --force
ENV PATH=/api/node_modules/.bin:$PATH

COPY tsconfig.json ./

COPY src ./src

EXPOSE ${PORT}

CMD ["npm","run","start:watch"]