name: CodeCov

on:
  push:
    branches: [codecov]
  pull_request:
    branches: [codecov]
jobs:
  build:
    name: Check source code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Run tests and collect coverage
      run: pytest --cov=api.calculator --cov-report=xml
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3