name: CodeCov

on:
  push:
    branches: [codecov]
  pull_request:
    branches: [codecov]
jobs:
  build:
    name: Check source code
    runs-on: ubuntu-latest
    steps:
      -name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version v12
      - name: Install packages
        run: npm install
      -name: Run tests
        run: npm run test
      -name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
      
