name: CodeCov

on:
  push:
    branches: [codecov_mocha]
  pull_request:
    branches: [codecov_mocha]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install packages
        working-directory: ./api
        run: npm install
      - name: Run test
        working-directory: ./api
        run: npm test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          #files: ./coverage1.xml
    
 
  
