name: CodeCov

on:
  push:
    branches: [codecov]
  pull_request:
    branches: [codecov]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 12
      - name: Install packages
        run: npm install
    
 
      
