name: Lint

on: [push]

jobs:
  build: 
    name: Check source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
      - run: npm ci
      - name: Lint
      - run: npm run lint