name: Lint

on: 
  pull_request:
    branches: [dev, prod]

jobs:
  build: 
    name: Check source code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        working-directory: ./api/src
        run: npm ci
      - name: Lint
        working-directory: ./api/src
        run: npm run lint